// Questions list
let questions = [
  "Have you contracted Covid at all during the pandemic?",
  "Have you recently felt a shortness of breath?",
  "Have you recently had difficulty breathing?",
  "Do you have any respiratory issues?",
  "Have you experienced any chills?",
  "Have you experienced a significant amount of fatigue or weakness?",
  "Have you experienced any severe headaches/fever?",
  "Have you experienced any aching within the body/muscles?",
  "Do you go out often but don't interact/ go near other people?",
  "Do you go out often and interact/ go near other people?",
  "Sex?",
  "Do you smoke cigarettes?",
  "Devils Lettuce?",
  "Columbian angel fairy dust?",
  "Blue sky?",
  "Ketamine?",
  "Have you acquired a new addiction because of covid?",
  "Mango Flavoured Addiction?",
  "Have you drank above 5 gallons of alcohol just cuz #whynot?",
  "Have you drank below 5 metric tons of alcohol because you aren't cool enough?",
  "Have you experienced any coughing recently?",
  "Has any form of coughing come from smoking habits?",
  "Do you experience any chest pain?",
  "Do you experience any memory problems?",
  "Do you experience any memory problems?",
  "Do you experience any memory problems?",
  "Do you experience any memory problems?",
  "Have you had any memory problems before the pandemic started?",
  "Do you remember your lifestyle before the pandemic started?",
  "Do you often ponder about the origins of this disease?",
  "I believe this virus was man-made and anybody who doesn't agree is an idiot",
  "I believe this virus was not man-made and anybody who doesn't agree is an idiot",
  "I believe this virus is real",
  "Fake?",
  "Conspiracy?",
  "Has Covid made you more philosophical?",
  "Has Covid made you more intelligent?",
  "Has Covid made you more attractive?",
  "Ugly?",
  "Down Bad?",
  "Based and Red-pilled?",
  "Has Covid made you more racist?",
  "Do you hate China?",
  "Does China hate you?",
  "Do you blame China for Covid?",
  "Do you blame anti maskers for the spread of Covid?",
  "Are you an anti masker?",
  "Do you always wear a mask in a public place?",
  "Do you blame teenagers for the spread of Covid?",
  "Do you blame yourself for the spread of Covid?",
  "Have you gotten the vaccine?",
  "Will you take the vaccine in the future?",
  "Do you question the legitimacy of the vaccine?",
  "I am educated about the science behind the covid vaccine",
  "My perception of the vaccine is built upon facebook posts that my grandparents send me",
  "If the vaccine would make you grow a third arm, would you accept it?",
  "Will you use your third arm for good?",
  "Will you use your third arm for bad?",
  "Will you use the new arm to become a god at sports",
  "Will you use the new arm to take over Albania?",
  "Will you use your third arm to defend Albania?",
];
