// Questions list
let questions = [
  "Have you contracted Covid at all during the pandemic?",
  "Have you recently felt a shortness of breath?",
  "Have you recently had difficulty breathing?",
  "Do you have any respiratory issues?",
  "Have you experienced any chills?",
  "Have you experienced a significant amount of fatigue or weakness?",
  "Have you experienced any severe headaches/fever?",
  "Have you experienced any aching within the body/muscles?",
  "Do you go out often but don't interact/ go near other people?",
  "Do you go out often and interact/ go near other people?",
  "Sex?",
  "Do you smoke cigarettes?",
  "Devils Lettuce?",
  "Columbian angel fairy dust?",
  "Blue sky?",
  "Ketamine?",
  "Have you acquired a new addiction because of covid?",
  "Mango Flavoured Addiction?",
  "Have you drank above 5 gallons of alcohol just cuz #whynot?",
  "Have you drank below 5 metric tons of alcohol because you aren't cool enough?",
  "Have you experienced any coughing recently?",
  "",
  "",
  "",
